routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Auth::routes();

Route::get('/home', function(){
	return redirect('/');
});

Route::get('/privacidade_e_termos', 'PagesController@privacy');

Route::get('/','PagesController@index');

Route::get('/register/confirm/{token}','PagesController@verifyEmail');

// SOCIALITE
Route::get('facebook', function () {
    return view('facebook');
});
Route::get('auth/{provider}', 'Auth\AuthController@redirectToProvider');
Route::get('auth/{provider}/callback', 'Auth\AuthController@handleProviderCallback');
// END SOCIALITE

Route::group([], function(){	
	Route::group(['prefix' => 'pesquisa'], function(){
		Route::get('{uuid}','SurveysController@show');
	});
});

Route::group(['middleware'=>'auth'], function(){
	Route::get('/send-verification-email','PagesController@sendVerificationEmail');
});

Route::get('pesq/{uuid}', 'SurveysController@APIshow');

Route::group(['prefix'=>'admin','middleware'=>'auth'], function(){
	Route::get('/','PagesController@index');
});

app/User.php
<?php

namespace App;

use Laravel\Passport\HasApiTokens;
use Illuminate\Notifications\Notifiable;
use Illuminate\Foundation\Auth\User as Authenticatable;

class User extends Authenticatable
{
    use HasApiTokens, Notifiable;

    public static function boot()
    {
        parent::boot();

        static::creating( function ($user) {
            $user->token = str_random(30);
        });
    }

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name',
        'email',
        'password',
        'state_id',
        'city_id',
        'gender',
        'verified',
        'birth',
        'provider',
        'provider_id',
        'avatar'
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];

    public function confirmEmail()
    {
        $this->verified = 1;
        $this->token = null;
        $this->save();
    }

    public function addNew($input)
    {
        $check = static::where('facebook_id',$input['facebook_id'])->first();

        if(is_null($check)){
            return static::create($input);
        }

        return $check;
    }

    public function getAvatarImageAttribute(){
        return $this->avatar?:asset('/img/users/user.jpg');
    }

}

resources/views/front/partials/topbar.blade.php
<nav class="topbar fixed-top navbar navbar-expand-md navbar-dark navbar-laravel">
    <div class="container">
        <a class="navbar-brand" href="{{ url('/') }}">
            <span>i</span>Pesquisa
        </a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>

        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <!-- Left Side Of Navbar -->
            <ul class="navbar-nav mr-auto">

            </ul>

            <!-- Right Side Of Navbar -->
            <ul class="navbar-nav ml-auto">
                <!-- Authentication Links -->
                @guest
                    <li><a class="nav-link signup" href="{{ route('register') }}">{{ __('Cadastar') }}</a></li>
                    <li><a class="nav-link signin" href="{{ route('login') }}">{{ __('Entrar') }}</a></li>
                @else
                    <li class="nav-item dropdown">
                        <a id="navbarDropdown" class="nav-link dropdown-toggle username" href="#" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" v-pre>
                            {{ Auth::user()->name }}<span class="caret"></span>
                            <img class="rounded-circle
" style="max-width: 30px; margin: 0 10px;" src="{{ Auth::user()->avatar_image }}" alt="">
                        </a>

                        <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
                            <a class="dropdown-item" href="{{ route('logout') }}"
                               onclick="event.preventDefault();
                                             document.getElementById('logout-form').submit();">
                                {{ __('Sair') }}
                            </a>

                            <form id="logout-form" action="{{ route('logout') }}" method="POST" style="display: none;">
                                @csrf
                            </form>
                        </div>
                    </li>
                @endguest
            </ul>
        </div>
    </div>
</nav>